version: '3.7'

services:

  hoppscotch-aio:
    container_name: hoppscotch-aio
    image: hoppscotch/hoppscotch:2023.12.6
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "3100:3100"
      - "3170:3170"